name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
        exclude:
          - os: ubuntu-latest  # Ubuntu-latest can only install 3.7+.
            python-version: 3.6
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r requirements-optional.txt

      - name: Lint
        run: |
          pip install --upgrade black mypy
          black --check --diff green example
          mypy .
        if: matrix.python-version == '3.11' && matrix.os == 'ubuntu-latest'

      - name: Test
        run: |
          python -m green.cmdline -tvvvv green
          cd example && python -m green.cmdline -tvvvv proj

      - name: Generate coverage
        run: |
          pip install --upgrade coveralls
          ./g -tvvvvr green
        if: matrix.python-version == '3.11' && matrix.os == 'ubuntu-latest'

      - name: Coveralls
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.python-version == '3.11' && matrix.os == 'ubuntu-latest'
