name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r requirements-optional.txt

      - name: Lint with black
        run: |
          pip install --upgrade black
          black --check --diff green
        if: matrix.python-version == '3.9' && matrix.os == 'ubuntu-latest'

      - name: Test
        run: python -m green.cmdline -tvvv green
        if: matrix.python-version != '3.9' || matrix.os != 'ubuntu-latest'

      - name: Generate coverage
        run: |
          pip install --upgrade coveralls
          ./g -tvvvr green
        if: matrix.python-version == '3.9' && matrix.os == 'ubuntu-latest'

      - name: Coveralls
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.python-version == '3.9' && matrix.os == 'ubuntu-latest'
