name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest] # Windows is handled in ci-windows.yml
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements-optional.txt
          pip install black virtualenv coveralls

      - name: Lint with black
        run: black --check --diff green

      - name: Test
        run: ./g -tvvv green

      - name: Generate coverage
        run: ./g -tr green
        if: matrix.python-version == '3.8' && matrix.os == 'ubuntu-latest'

      - name: Coveralls
        run: coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.python-version == '3.8' && matrix.os == 'ubuntu-latest'
