name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install black virtualenv coveralls

      - name: Lint with black
        run: black --check

      - name: Test
        run: ./g -vvv green

      - name: Generate coverage
        run: ./g -r green
        if: matrix.python-version == '3.8' && matrix.os == 'ubuntu-latest'

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.python-version == '3.8' && matrix.os == 'ubuntu-latest'
